sudo: required
language: ruby
cache: bundler

notifications:
  email:
    recipients:
      - ramitsurana@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --allow-redirect --white-list developer.ibm.com,linkedin.com,blog.kcluster.io,telepresence.io,kismatic.com,slideshare.net,research.google.com,kubespray.io,twitter.com,img.shields.io --allow-dupe
